### ISSUE TITLE
Titanium SDK 4.0.0 compatibility

### ISSUE THREAD

**Issue by hansemannn** [timanrebel/Parse#19]
Unfortunately, the android module is not working for me anymore, when using the latest Ti.SDK 4.0.0.RC (http://abload.de/img/bildschirmfoto2015-055fb2z.png). Would be great to be fixed!

**Comment by timanrebel** [comment]
I don't have access to Ti 4.0.0, but when I do or when it comes out I will try and fix it asap!

**Comment by hansemannn** [comment]
Check 4.0.0.RC2: http://builds.appcelerator.com.s3.amazonaws.com/index.html

**Comment by hansemannn** [comment]
Any update here? Having a customer request here. Thank you!

**Comment by timanrebel** [comment]
@jvandijk just did a PR that should fix it. My apologies for not doing it sooner

**Comment by hansemannn** [comment]
No problem, glad to have a solution! :-) Unfortunately, the build fails using the latest 4.1.0.GA SDK and studio:

```
[INFO] :   Running dexer: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java "-Xmx1024M" "-XX:-UseGCOverheadLimit" "-Djava.ext.dirs=/Users/hans/Library/android-sdk-macosx/platform-tools" "-jar" "/Users/hans/Library/android-sdk-macosx/build-tools/21.1.2/lib/dx.jar" "--dex" "--output=/Users/hans/Documents/ncnapps/festival/build/android/bin/classes.dex" "/Users/hans/Documents/ncnapps/festival/build/android/bin/classes" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/lib/titanium-verify.jar" "/Users/hans/Library/Application Support/Titanium/modules/android/facebook/4.0.5/facebook.jar" "/Users/hans/Library/Application Support/Titanium/modules/android/facebook/4.0.5/lib/bolts-android-1.1.2.jar" "/Users/hans/Library/Application Support/Titanium/modules/android/facebook/4.0.5/lib/facebooksdk.jar" "/Users/hans/Library/Application Support/Titanium/modules/android/ti.map/2.3.1/map.jar" "/Users/hans/Library/Application Support/Titanium/modules/android/ti.map/2.3.1/lib/google-play-services.jar" "/Users/hans/Documents/ncnapps/festival/modules/android/eu.rebelcorp.parse/0.7/parse.jar" "/Users/hans/Documents/ncnapps/festival/modules/android/eu.rebelcorp.parse/0.7/lib/Parse-1.7.1.jar" "/Users/hans/Documents/ncnapps/festival/modules/android/eu.rebelcorp.parse/0.7/lib/bolts-android-1.1.3.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/kroll-v8.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-analytics.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/aps-analytics.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-android.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/jaxen-1.1.1.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/ti-commons-codec-1.3.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/kroll-common.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/titanium.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-app.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-ui.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/nineoldandroids-appc-2.4.0.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-filesystem.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-media.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-appcompat.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/android-support-v4.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/android-support-v7-appcompat.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-locale.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-network.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/thirdparty.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-xml.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-utils.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-geolocation.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-accelerometer.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-contacts.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-map.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-calendar.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-gesture.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-platform.jar" "/Users/hans/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/modules/titanium-database.jar"
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lbolts/AggregateException;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  1 error; aborting
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/hans/.appcelerator/install/4.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[ERROR] Application Installer abnormal process termination. Process exit value was 1
```

**Comment by jvandijk** [comment]
@hansemannn I've tested it under 4.1.0.GA as well. The only difference I see is the Java version I run `jdk1.7.0_80.jdk` where you have `jdk1.8.0_40.jdk`.

**Comment by hansemannn** [comment]
Strange...Is your CLI at 4.1.0, too? Cannot get a workaround.

**Comment by jvandijk** [comment]
I already see the issue... there is a conflict with the Facebook module. That loads bolts 1.1.2 and the Parse module loads 1.1.3.
I have no solution for that unfortunately.

**Comment by hansemannn** [comment]
Can I use the 1.1.2 locally or does Parse makes problems than?

**Comment by timanrebel** [comment]
Parse supports GCM nowadays, so using https://github.com/iamyellow/gcm.js/tree/master combined with Parse's REST API might be an alternative

**Comment by hansemannn** [comment]
My last status was, that it is not possible to register an Android device using the REST-API (iOS is ok).

**Comment by jvandijk** [comment]
You could try to build your own version based on Parse 1.7.0. That one does not use bolts yet and should not differ that much from the current used version 1.7.1.

**Comment by beaurushton** [comment]
Is there a solution for this going forward?  I see that Parse SDK 1.9.4 is used, can I simply replace with v1.7 or is there new features that require the update?  Unfortunately my app also needs to use Facebook module...

**Comment by jvandijk** [comment]
@hansemannn @beaurushton version 0.12.0 now is inline with ti.facebook version 5.0.0. Both modules depend on version 1.2.1 of the Bolts library which will make them work together.

**Comment by nitrag** [comment]
Thanks so much! Have been looking forward to this compatibility!

**Comment by beaurushton** [comment]
Yes very much appreciated!  Thank you!
